version: '3'

services: 

  mongo:
    container_name: iai2-oven-database-mongo
    image: mongo
    ports: 
      - '27017:27017'
    volumes: 
      - ~/mongo/data:/data/db 
  
  server-api:
    container_name: iai2-oven-node-api
    restart: always
    build: .
    ports:
      - '5000:5000'
    links: 
      - mongo
    environment: 
      - API_PORT=5000
      - DB_ADDRESS=mongodb://mongo:27017/iai2-oven
  